Box-model exercise
EstefaSora125/css-tutorial pull request #3
Opened 2020-05-18 04:21 UTC by EstefaSora125

Box- model exercise by Estefania Sora

2020-05-19 14:22 UTC, pushdev-code requested changes
good job! just a couple of comments.

2020-05-19 14:22 UTC, pushdev-code commented on 3-box-model/box-model.html
> +    <main>
nice! you're using semantic elements.

2020-05-19 14:22 UTC, pushdev-code commented on 3-box-model/style.css
> +    position: sticky;
this element is not being visually sticky, can you guess what you're missing to make it work? clue: it's a top property.

2020-05-19 14:22 UTC, pushdev-code commented on 3-box-model/style.css
> +}
```suggestion
```
you don't need this, remove it.

2020-05-24 17:05 UTC, pushdev-code approved these changes

2020-05-24 17:05 UTC, fabianmarinog approved these changes

2020-05-24 17:05 UTC, merged